### ISSUE TITLE
Help running container, runc error can not find

### ISSUE THREAD

**Issue by hurricanehrndz** [multiarch/debian-debootstrap#3]
Whenever I try and run the any of the debootstrap images just to run uname, I get the following:
```
docker run -it --rm multiarch/debian-debootstrap:armhf-jessie
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
        panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x6f1b40, 0xc420133ab0)
        /usr/lib64/go/src/runtime/panic.go:500 +0x1a1
github.com/urfave/cli.HandleAction.func1(0xc420089748)
        /home/abuild/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x247
panic(0x6f1b40, 0xc420133ab0)
        /usr/lib64/go/src/runtime/panic.go:458 +0x243
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc420089198, 0xc420026098, 0xc420089238)
        /home/abuild/go/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x18f
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc420057400, 0xaa69c0, 0xc420133ab0)
        /home/abuild/go/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x353
main.glob..func8(0xc42008ca00, 0x0, 0x0)
        /home/abuild/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x66
reflect.Value.call(0x6dc8c0, 0x768390, 0x13, 0x73ac29, 0x4, 0xc420089708, 0x1, 0x1, 0x4d1128, 0x730a80, ...)
        /usr/lib64/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x6dc8c0, 0x768390, 0x13, 0xc420089708, 0x1, 0x1, 0xabc700, 0xc4200896e8, 0x4da106)
        /usr/lib64/go/src/reflect/value.go:302 +0xa4
github.com/urfave/cli.HandleAction(0x6dc8c0, 0x768390, 0xc42008ca00, 0x0, 0x0)
        /home/abuild/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x1e0
github.com/urfave/cli.Command.Run(0x73adf9, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x74c34c, 0x51, 0x0, ...)
        /home/abuild/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xc3b
github.com/urfave/cli.(*App).Run(0xc4200d8000, 0xc42000c120, 0x2, 0x2, 0x0, 0x0)
        /home/abuild/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x611
main.main()
        /home/abuild/go/src/github.com/opencontainers/runc/main.go:137 +0xbd6
```

I also did register the binfmt first
````
» docker run --rm --privileged multiarch/qemu-user-static:register                  
Unable to find image 'multiarch/qemu-user-static:register' locally
register: Pulling from multiarch/qemu-user-static
56bec22e3559: Pull complete
83ec6893d7c2: Pull complete
Digest: sha256:73704ec275a829d011130d4200e4b4351ba27b6b6c8dd07428583736ef714e19
Status: Downloaded newer image for multiarch/qemu-user-static:register
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
sh: write error: File exists
```
```
» cat /proc/sys/fs/binfmt_misc/arm             
enabled
interpreter /usr/bin/qemu-arm-binfmt
flags: P
offset 0
magic 7f454c4601010100000000000000000002002800
mask ffffffffffffff00fffffffffffffffffeffffff
```

**Comment by hurricanehrndz** [comment]
Sorry, I had run my systems binfmt register and I had a qemu chroot environment that caused some issues.

**Comment by moul** [comment]
No problem, happy that you fixed it by yourself
